In [1]:
#Data frames are made up of 1 or more series
#Name of the series are the column names
#Index are the row numbers

In [9]:
import pandas as pd

meteorites = pd.read_csv('../data/Meteorite_Landings.csv',nrows=3)
meteorites

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"

In [8]:
import pandas as pd

meteorites = pd.read_csv('../data/Meteorite_Landings.csv',nrows=3)
meteorites.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"

In [10]:
#Series
meteorites.name

0    Aachen
1    Aarhus
2      Abee
Name: name, dtype: object

In [15]:
#Columns
meteorites.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass (g)', 'fall', 'year',
       'reclat', 'reclong', 'GeoLocation'],
      dtype='object')

In [16]:
meteorites.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
#Creating Data Frames
#Can be done from sources such as other 
#Python objects
#flat files
#webscraping
#and API requests.

In [2]:
#Flat File

import pandas as pd

meteorites = pd.read_csv('../data/Meteorite_Landings.csv')

In [ ]:
#API
import requests

response = requests.get(
    'https://data.nasa.gov/resource/gh4g-9sfh.json',
    params={'$limit': 50_000}
)

if response.ok:
    payload = response.json()
else:
    print(f'Request was not successful and returned code: {response.status_code}.')
    payload = None

In [ ]:
import pandas as pd

df = pd.DataFrame(payload)
df.head(3)

In [20]:
#DataFrame Inspection

#Rows and Colummn
meteorites.shape

(45716, 10)

In [21]:
#Colummns

meteorites.columns

Index(['name', 'id', 'nametype', 'recclass', 'mass (g)', 'fall', 'year',
       'reclat', 'reclong', 'GeoLocation'],
      dtype='object')

In [22]:
#DatTypes

meteorites.dtypes

name            object
id               int64
nametype        object
recclass        object
mass (g)       float64
fall            object
year            object
reclat         float64
reclong        float64
GeoLocation     object
dtype: object

In [24]:
#General Info
meteorites.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45716 entries, 0 to 45715
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         45716 non-null  object
 1   id           45716 non-null  int64
 2   nametype     45716 non-null  object
 3   recclass     45716 non-null  object
 4   mass (g)     45585 non-null  float64
 5   fall         45716 non-null  object
 6   year         45425 non-null  object
 7   reclat       38401 non-null  float64
 8   reclong      38401 non-null  float64
 9   GeoLocation  38401 non-null  object
dtypes: float64(3), int64(1), object(6)
memory usage: 3.5+ MB

In [26]:
#upper view

meteorites.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [27]:
#bottom view

meteorites.tail()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
45711,Zillah 002,31356,Valid,Eucrite,172.0,Found,01/01/1990 12:00:00 AM,29.03700,17.01850,"(29.037, 17.0185)"
45712,Zinder,30409,Valid,"Pallasite, ungrouped",46.0,Found,01/01/1999 12:00:00 AM,13.78333,8.96667,"(13.78333, 8.96667)"
45713,Zlin,30410,Valid,H4,3.3,Found,01/01/1939 12:00:00 AM,49.25000,17.66667,"(49.25, 17.66667)"
45714,Zubkovsky,31357,Valid,L6,2167.0,Found,01/01/2003 12:00:00 AM,49.78917,41.50460,"(49.78917, 41.5046)"
45715,Zulu Queen,30414,Valid,L3.7,200.0,Found,01/01/1976 12:00:00 AM,33.98333,-115.68333,"(33.98333, -115.68333)"

Exercise 1
Create a DataFrame by reading in the 2019_Yellow_Taxi_Trip_Data.csv file. Examine the first 5 rows.

In [3]:
# import package_name
import pandas as pd

# read file to variable
df = pd.read_csv('../data/2019_Yellow_Taxi_Trip_Data.csv')

# print the first 5 rows
df.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,N,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,N,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,N,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,N,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,N,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5

Exercise 2
Find the dimensions (number of rows and number of columns) in the data.

In [34]:
df.shape

(10000, 18)

Extracting subsets¶
A crucial part of working with DataFrames is extracting subsets of the data: finding rows that meet a certain set of criteria, isolating columns/rows of interest, etc.
After narrowing down our data, we are closer to discovering insights. This section will be the backbone of many analysis tasks.

In [38]:
#Selecting a column
df.vendorid

0       2
1       1
2       2
3       2
4       2
       ..
9995    1
9996    1
9997    1
9998    1
9999    1
Name: vendorid, Length: 10000, dtype: int64

In [39]:
#Multiple columns
df[['vendorid','extra']]

      vendorid  extra
0            2    1.0
1            1    1.0
2            2    1.0
3            2    1.0
4            2    1.0
...        ...    ...
9995         1    3.5
9996         1    3.5
9997         1    1.0
9998         1    1.0
9999         1    3.5

[10000 rows x 2 columns]

In [40]:
#Selecting Rows
df[10:20]

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
10,1,2019-10-23T16:35:02.000,2019-10-23T17:57:38.000,2,18.20,2,N,230,132,1,52.0,7.0,0.5,6.00,6.12,0.3,71.92,2.5
11,1,2019-10-23T16:17:33.000,2019-10-23T16:32:58.000,1,2.10,1,N,79,162,1,11.5,3.5,0.5,2.00,0.00,0.3,17.80,2.5
12,1,2019-10-23T16:35:45.000,2019-10-23T16:39:14.000,1,0.70,1,N,170,233,2,4.5,3.5,0.5,0.00,0.00,0.3,8.80,2.5
13,2,2019-10-23T16:34:52.000,2019-10-23T16:47:38.000,1,2.86,1,N,229,113,1,11.5,1.0,0.5,3.16,0.00,0.3,18.96,2.5
14,2,2019-10-23T16:49:24.000,2019-10-23T16:59:20.000,2,1.32,1,N,113,211,1,8.0,1.0,0.5,2.46,0.00,0.3,14.76,2.5
15,2,2019-10-23T17:01:08.000,2019-10-23T17:18:22.000,1,1.99,1,N,144,170,1,12.0,1.0,0.5,4.89,0.00,0.3,21.19,2.5
16,2,2019-10-23T16:07:34.000,2019-10-23T16:12:48.000,2,1.13,1,N,151,166,2,-5.5,-1.0,-0.5,0.00,0.00,-0.3,-7.30,0.0
17,2,2019-10-23T16:07:34.000,2019-10-23T16:12:48.000,2,1.13,1,N,151,166,2,5.5,1.0,0.5,0.00,0.00,0.3,7.30,0.0
18,2,2019-10-23T16:21:32.000,2019-10-23T16:33:02.000,2,2.94,1,N,151,50,1,11.5,1.0,0.5,0.00,0.00,0.3,15.80,2.5
19,2,2019-10-23T16:45:33.000,2019-10-23T16:48:49.000,1,0.70,1,N,143,239,1,4.5,1.0,0.5,1.00,0.00,0.3,9.80,2.5

Indexing
We use iloc[] to select rows and columns by their position:

In [43]:
df.iloc[10:20,[0,1,2,3]]

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count
10,1,2019-10-23T16:35:02.000,2019-10-23T17:57:38.000,2
11,1,2019-10-23T16:17:33.000,2019-10-23T16:32:58.000,1
12,1,2019-10-23T16:35:45.000,2019-10-23T16:39:14.000,1
13,2,2019-10-23T16:34:52.000,2019-10-23T16:47:38.000,1
14,2,2019-10-23T16:49:24.000,2019-10-23T16:59:20.000,2
15,2,2019-10-23T17:01:08.000,2019-10-23T17:18:22.000,1
16,2,2019-10-23T16:07:34.000,2019-10-23T16:12:48.000,2
17,2,2019-10-23T16:07:34.000,2019-10-23T16:12:48.000,2
18,2,2019-10-23T16:21:32.000,2019-10-23T16:33:02.000,2
19,2,2019-10-23T16:45:33.000,2019-10-23T16:48:49.000,1

We use loc[ ] to select by name

In [46]:
df.loc[10:20,'vendorid':'extra']

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra
10,1,2019-10-23T16:35:02.000,2019-10-23T17:57:38.000,2,18.20,2,N,230,132,1,52.0,7.0
11,1,2019-10-23T16:17:33.000,2019-10-23T16:32:58.000,1,2.10,1,N,79,162,1,11.5,3.5
12,1,2019-10-23T16:35:45.000,2019-10-23T16:39:14.000,1,0.70,1,N,170,233,2,4.5,3.5
13,2,2019-10-23T16:34:52.000,2019-10-23T16:47:38.000,1,2.86,1,N,229,113,1,11.5,1.0
14,2,2019-10-23T16:49:24.000,2019-10-23T16:59:20.000,2,1.32,1,N,113,211,1,8.0,1.0
15,2,2019-10-23T17:01:08.000,2019-10-23T17:18:22.000,1,1.99,1,N,144,170,1,12.0,1.0
16,2,2019-10-23T16:07:34.000,2019-10-23T16:12:48.000,2,1.13,1,N,151,166,2,-5.5,-1.0
17,2,2019-10-23T16:07:34.000,2019-10-23T16:12:48.000,2,1.13,1,N,151,166,2,5.5,1.0
18,2,2019-10-23T16:21:32.000,2019-10-23T16:33:02.000,2,2.94,1,N,151,50,1,11.5,1.0
19,2,2019-10-23T16:45:33.000,2019-10-23T16:48:49.000,1,0.70,1,N,143,239,1,4.5,1.0
20,1,2019-10-23T16:11:23.000,2019-10-23T16:16:18.000,1,0.40,1,N,161,164,1,5.0,3.5

Filtering with Boolean masks
A Boolean mask is a array-like structure of Boolean values 
– it's a way to specify which rows/columns we want to select (True) and which we don't (False).

In [49]:
(df.fare_amount > 25)

0        True
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: fare_amount, Length: 10000, dtype: bool

Calculating Summary Statistics

In [4]:
#Finding the counts

df.store_and_fwd_flag.value_counts()

store_and_fwd_flag
N    9838
Y     162
Name: count, dtype: int64

What was the average trip distance?

In [7]:
df['trip_distance'].mean()

np.float64(3.01525)

Quantile

In [8]:
df['trip_distance'].quantile([0.01, 0.05, 0.5, 0.95, 0.99])

0.01     0.0000
0.05     0.4300
0.50     1.5000
0.95    13.7225
0.99    19.3000
Name: trip_distance, dtype: float64

Median

In [9]:
df['trip_distance'].median()

np.float64(1.5)

Longest Journey

In [12]:
df['trip_distance'].max()

np.float64(38.11)

Further info on the Longest Journey

In [13]:
df.loc[df['trip_distance'].idxmax()]

vendorid                                       2
tpep_pickup_datetime     2019-10-23T16:50:53.000
tpep_dropoff_datetime    2019-10-24T15:32:55.000
passenger_count                                1
trip_distance                              38.11
ratecodeid                                     5
store_and_fwd_flag                             N
pulocationid                                 132
dolocationid                                 265
payment_type                                   1
fare_amount                                176.0
extra                                        0.0
mta_tax                                      0.5
tip_amount                                 18.29
tolls_amount                                6.12
improvement_surcharge                        0.3
total_amount                              201.21
congestion_surcharge                         0.0
Name: 8338, dtype: object

Summary Statistics

In [27]:
df.describe(include=[float])

,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,3.015250,15.106313,1.960235,0.492450,2.634494,0.623447,0.298140,22.564659,2.282800
std,4.148063,13.954762,1.392940,0.071544,3.409800,6.437507,0.032537,19.209255,0.720946
min,0.000000,-52.000000,-4.500000,-0.500000,0.000000,-6.120000,-0.300000,-65.920000,-2.500000
25%,0.920000,7.000000,1.000000,0.500000,0.000000,0.000000,0.300000,12.375000,2.500000
50%,1.500000,10.000000,1.000000,0.500000,2.000000,0.000000,0.300000,16.300000,2.500000
75%,2.760000,16.000000,3.500000,0.500000,3.250000,0.000000,0.300000,22.880000,2.500000
max,38.110000,176.000000,7.000000,0.500000,43.000000,612.000000,0.300000,671.800000,2.750000

In [28]:
#for specific columns

df[['fare_amount', 'tip_amount', 'tolls_amount','total_amount']].describe()

        fare_amount    tip_amount  tolls_amount  total_amount
count  10000.000000  10000.000000  10000.000000  10000.000000
mean      15.106313      2.634494      0.623447     22.564659
std       13.954762      3.409800      6.437507     19.209255
min      -52.000000      0.000000     -6.120000    -65.920000
25%        7.000000      0.000000      0.000000     12.375000
50%       10.000000      2.000000      0.000000     16.300000
75%       16.000000      3.250000      0.000000     22.880000
max      176.000000     43.000000    612.000000    671.800000

Isolate the fare_amount, tip_amount, tolls_amount, and total_amount for the longest trip by distance (trip_distance).

In [54]:
#Logest distance

# Find the index of the oldest person
index_longest = df['trip_distance'].idxmax()

# Get height, weight, and salary directly
result = df.loc[index_longest, ['fare_amount', 'tip_amount', 'total_amount', 'tolls_amount']]
print(result)

fare_amount      176.0
tip_amount       18.29
total_amount    201.21
tolls_amount      6.12
Name: 8338, dtype: object