Data Wrangling 1

This section includes:
Data cleaning and formatting (Renaming columns and fixing data type mismatches)
Data Restructuring & Reshaping (Discretizing columns, calculating aggregations, and combining data sources).

In [7]:
import pandas as pd

taxis = pd.read_csv('../data/2019_Yellow_Taxi_Trip_Data.csv')
taxis.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,N,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,N,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,N,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,N,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,N,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5

Dropping columns
Drop ID columns and the store_and_fwd_flag column

In [8]:
columns_to_drop = ['vendorid', 'ratecodeid', 'pulocationid','dolocationid','store_and_fwd_flag']
taxis = taxis.drop(columns=columns_to_drop)
taxis.head()

,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5

Renaming columns
Next, let's rename the datetime columns:

In [9]:
taxis = taxis.rename(
    columns={
        'tpep_pickup_datetime': 'pickup', 
        'tpep_dropoff_datetime': 'dropoff'
    }
)
taxis.columns

Index(['pickup', 'dropoff', 'passenger_count', 'trip_distance', 'payment_type',
       'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount',
       'improvement_surcharge', 'total_amount', 'congestion_surcharge'],
      dtype='object')

Type conversion
Notice anything off with the data types?

In [11]:
taxis.dtypes

pickup                    object
dropoff                   object
passenger_count            int64
trip_distance            float64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object

In [12]:
#Convert picup and dropoff to datetime

taxis[['pickup', 'dropoff']] = taxis[['pickup', 'dropoff']].apply(pd.to_datetime)

taxis.dtypes

pickup                   datetime64[ns]
dropoff                  datetime64[ns]
passenger_count                   int64
trip_distance                   float64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
dtype: object

Creating new columns
There are multiple ways to create columns using pandas, here we will look at two methods, standard formula and lambda functions.

In [13]:
taxis['new_column1'] = 'This is a new column'
taxis = taxis.assign(new_column2 = lambda x: 'This is a new column too')
taxis.head(2)

,pickup,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,new_column1,new_column2
0,2019-10-23 16:39:42,2019-10-23 17:14:10,1,7.93,1,29.5,1.0,0.5,7.98,6.12,0.3,47.9,2.5,This is a new column,This is a new column too
1,2019-10-23 16:32:08,2019-10-23 16:45:26,1,2.00,1,10.5,1.0,0.5,0.00,0.00,0.3,12.3,0.0,This is a new column,This is a new column too

We can create new columns based on existing columns too.

Note how 'x' in the lambda function refers to 'taxis' dataframe.

In [14]:
# Trip Time
taxis['trip_time1'] = taxis['dropoff'] - taxis['pickup']
taxis = taxis.assign(trip_time2 = lambda x: x.dropoff - x.pickup)
taxis.head(2)

,pickup,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,new_column1,new_column2,trip_time1,trip_time2
0,2019-10-23 16:39:42,2019-10-23 17:14:10,1,7.93,1,29.5,1.0,0.5,7.98,6.12,0.3,47.9,2.5,This is a new column,This is a new column too,0 days 00:34:28,0 days 00:34:28
1,2019-10-23 16:32:08,2019-10-23 16:45:26,1,2.00,1,10.5,1.0,0.5,0.00,0.00,0.3,12.3,0.0,This is a new column,This is a new column too,0 days 00:13:18,0 days 00:13:18

Let's calculate the following for each row:

elapsed time of the trip
the tip percentage
the total taxes, tolls, fees, and surcharges
the average speed of the taxi

In [23]:
taxis = taxis.assign(
    elapsed_time=lambda x: x.dropoff - x.pickup, # 1
    cost_before_tip=lambda x: x.total_amount - x.tip_amount,
    tip_pct=lambda x: x.tip_amount / x.cost_before_tip, # 2
    fees=lambda x: x.cost_before_tip - x.fare_amount, # 3
    avg_speed=lambda x: x.trip_distance.div(
        x.elapsed_time.dt.total_seconds() / 60 / 60
    ) # 4
)
taxis.head(2)

,pickup,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,...,congestion_surcharge,new_column1,new_column2,trip_time1,trip_time2,elapsed_time,cost_before_tip,tip_pct,fees,avg_speed
0,2019-10-23 16:39:42,2019-10-23 17:14:10,1,7.93,1,29.5,1.0,0.5,7.98,6.12,...,2.5,This is a new column,This is a new column too,0 days 00:34:28,0 days 00:34:28,0 days 00:34:28,39.92,0.1999,10.42,13.804642
1,2019-10-23 16:32:08,2019-10-23 16:45:26,1,2.00,1,10.5,1.0,0.5,0.00,0.00,...,0.0,This is a new column,This is a new column too,0 days 00:13:18,0 days 00:13:18,0 days 00:13:18,12.30,0.0000,1.80,9.022556

Some things to note:

We used lambda functions to 1) avoid typing taxis repeatedly and 2) be able to access the cost_before_tip and elapsed_time columns in the same method that we create them.
To create a single new column, we can also use df['new_col'] = <values>.

Sorting by values
We can use the sort_values() method to sort based on any number of columns:

In [24]:
taxis.sort_values(['passenger_count', 'pickup'], ascending=[True, False]).head()

,pickup,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,...,congestion_surcharge,new_column1,new_column2,trip_time1,trip_time2,elapsed_time,cost_before_tip,tip_pct,fees,avg_speed
9355,2019-10-24 08:19:11,2019-10-24 09:00:35,0,13.2,2,42.0,0.0,0.5,0.00,0.0,...,0.0,This is a new column,This is a new column too,0 days 00:41:24,0 days 00:41:24,0 days 00:41:24,42.8,0.000000,0.8,19.130435
9432,2019-10-23 17:54:48,2019-10-23 18:08:56,0,1.3,1,10.0,3.5,0.5,2.85,0.0,...,2.5,This is a new column,This is a new column too,0 days 00:14:08,0 days 00:14:08,0 days 00:14:08,14.3,0.199301,4.3,5.518868
9697,2019-10-23 17:52:10,2019-10-23 17:58:24,0,0.9,1,6.0,3.5,0.5,2.05,0.0,...,2.5,This is a new column,This is a new column too,0 days 00:06:14,0 days 00:06:14,0 days 00:06:14,10.3,0.199029,4.3,8.663102
9633,2019-10-23 17:52:02,2019-10-23 17:58:20,0,1.0,1,6.0,3.5,0.5,1.00,0.0,...,2.5,This is a new column,This is a new column too,0 days 00:06:18,0 days 00:06:18,0 days 00:06:18,10.3,0.097087,4.3,9.523810
9516,2019-10-23 17:48:43,2019-10-23 18:07:36,0,1.9,1,13.0,3.5,0.5,1.50,0.0,...,2.5,This is a new column,This is a new column too,0 days 00:18:53,0 days 00:18:53,0 days 00:18:53,17.3,0.086705,4.3,6.037070

To pick out the largest/smallest rows, use nlargest() / nsmallest() instead. Looking at the 3 trips with the longest elapsed time, we see some possible data integrity issues:

In [25]:
taxis.nlargest(3, 'elapsed_time')

,pickup,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,...,congestion_surcharge,new_column1,new_column2,trip_time1,trip_time2,elapsed_time,cost_before_tip,tip_pct,fees,avg_speed
7576,2019-10-23 16:52:51,2019-10-24 16:51:44,1,3.75,1,17.5,1.0,0.5,0.0,0.0,...,2.5,This is a new column,This is a new column too,0 days 23:58:53,0 days 23:58:53,0 days 23:58:53,21.8,0.0,4.3,0.156371
6902,2019-10-23 16:51:42,2019-10-24 16:50:22,1,11.19,2,39.5,1.0,0.5,0.0,0.0,...,0.0,This is a new column,This is a new column too,0 days 23:58:40,0 days 23:58:40,0 days 23:58:40,41.3,0.0,1.8,0.466682
4975,2019-10-23 16:18:51,2019-10-24 16:17:30,1,0.70,2,7.0,1.0,0.5,0.0,0.0,...,2.5,This is a new column,This is a new column too,0 days 23:58:39,0 days 23:58:39,0 days 23:58:39,11.3,0.0,4.3,0.029194

Exercise 1¶
Read in the meteorite data from the Meteorite_Landings.csv file, rename the mass (g) column to mass, and drop all the latitude and longitude columns. Sort the result by mass in descending order.

In [26]:
import pandas as pd
meteorites=pd.read_csv('../data/Meteorite_Landings.csv')
meteorites.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [30]:
#Rename
meteorites=meteorites.rename(
    columns={'mass (g)':'mass'}


)
meteorites.head()

,name,id,nametype,recclass,mass,fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [35]:
#Drop Long/Lat
columns_to_drop = ['reclat','reclong']
meteorites=meteorites.drop(columns=columns_to_drop)
meteorites.head()

,name,id,nametype,recclass,mass,fall,year,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,"(-33.16667, -64.95)"

Working with the index
So far, we haven't really worked with the index because it's just been a row number;
however, we can change the values we have in the index to access additional features of the pandas library.

Setting and sorting the index
Currently, we have a RangeIndex, but we can switch to a DatetimeIndex by specifying a datetime column when calling set_index():

In [36]:
taxis = taxis.set_index('pickup')
taxis.head(3)

,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,...,congestion_surcharge,new_column1,new_column2,trip_time1,trip_time2,elapsed_time,cost_before_tip,tip_pct,fees,avg_speed
pickup,,,,,,,,,,,,,,,,,,,,,
2019-10-23 16:39:42,2019-10-23 17:14:10,1,7.93,1,29.5,1.0,0.5,7.98,6.12,0.3,...,2.5,This is a new column,This is a new column too,0 days 00:34:28,0 days 00:34:28,0 days 00:34:28,39.92,0.199900,10.42,13.804642
2019-10-23 16:32:08,2019-10-23 16:45:26,1,2.00,1,10.5,1.0,0.5,0.00,0.00,0.3,...,0.0,This is a new column,This is a new column too,0 days 00:13:18,0 days 00:13:18,0 days 00:13:18,12.30,0.000000,1.80,9.022556
2019-10-23 16:08:44,2019-10-23 16:21:11,1,1.36,1,9.5,1.0,0.5,2.00,0.00,0.3,...,2.5,This is a new column,This is a new column too,0 days 00:12:27,0 days 00:12:27,0 days 00:12:27,13.80,0.144928,4.30,6.554217

In [40]:
#Since we have a sample of the full dataset, let's sort the index to order by pickup time:
taxis = taxis.sort_index(ascending=False)
taxis.head()

,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,...,congestion_surcharge,new_column1,new_column2,trip_time1,trip_time2,elapsed_time,cost_before_tip,tip_pct,fees,avg_speed
pickup,,,,,,,,,,,,,,,,,,,,,
2019-10-24 08:19:11,2019-10-24 09:00:35,0,13.20,2,42.0,0.0,0.5,0.0,0.0,0.3,...,0.0,This is a new column,This is a new column too,0 days 00:41:24,0 days 00:41:24,0 days 00:41:24,42.8,0.0,0.8,19.130435
2019-10-24 08:07:45,2019-10-24 08:07:50,2,0.00,2,52.0,0.0,0.5,0.0,0.0,0.3,...,2.5,This is a new column,This is a new column too,0 days 00:00:05,0 days 00:00:05,0 days 00:00:05,55.3,0.0,3.3,0.000000
2019-10-24 07:58:31,2019-10-24 08:47:05,1,0.00,1,22.2,0.0,0.5,0.0,0.0,0.3,...,0.0,This is a new column,This is a new column too,0 days 00:48:34,0 days 00:48:34,0 days 00:48:34,23.0,0.0,0.8,0.000000
2019-10-24 07:29:52,2019-10-24 07:33:24,1,0.54,2,4.0,0.0,0.5,0.0,0.0,0.3,...,0.0,This is a new column,This is a new column too,0 days 00:03:32,0 days 00:03:32,0 days 00:03:32,4.8,0.0,0.8,9.169811
2019-10-24 07:23:52,2019-10-24 08:08:52,1,0.00,1,36.2,0.0,0.5,0.0,0.0,0.3,...,0.0,This is a new column,This is a new column too,0 days 00:45:00,0 days 00:45:00,0 days 00:45:00,37.0,0.0,0.8,0.000000

Tip: taxis.sort_index(axis=1) will sort the columns by name. The axis parameter is present throughout the pandas library: axis=0 targets rows and axis=1 targets columns.

We can now select ranges from our data based on the datetime the same way we did with row numbers:

In [39]:
taxis['2019-10-23 07:45':'2019-10-23 08']

,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,...,congestion_surcharge,new_column1,new_column2,trip_time1,trip_time2,elapsed_time,cost_before_tip,tip_pct,fees,avg_speed
pickup,,,,,,,,,,,,,,,,,,,,,
2019-10-23 07:48:58,2019-10-23 07:52:09,1,0.67,2,4.5,1.0,0.5,0.0,0.0,0.3,...,2.5,This is a new column,This is a new column too,0 days 00:03:11,0 days 00:03:11,0 days 00:03:11,8.8,0.000000,4.3,12.628272
2019-10-23 08:02:09,2019-10-24 07:42:32,1,8.38,1,32.0,1.0,0.5,5.5,0.0,0.3,...,2.5,This is a new column,This is a new column too,0 days 23:40:23,0 days 23:40:23,0 days 23:40:23,36.3,0.151515,4.3,0.353989
2019-10-23 08:18:47,2019-10-23 08:36:05,1,2.39,2,12.5,1.0,0.5,0.0,0.0,0.3,...,2.5,This is a new column,This is a new column too,0 days 00:17:18,0 days 00:17:18,0 days 00:17:18,16.8,0.000000,4.3,8.289017

In [41]:
#When not specifying a range, we use loc[]:

taxis.loc['2019-10-23 08']

,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,...,congestion_surcharge,new_column1,new_column2,trip_time1,trip_time2,elapsed_time,cost_before_tip,tip_pct,fees,avg_speed
pickup,,,,,,,,,,,,,,,,,,,,,
2019-10-23 08:18:47,2019-10-23 08:36:05,1,2.39,2,12.5,1.0,0.5,0.0,0.0,0.3,...,2.5,This is a new column,This is a new column too,0 days 00:17:18,0 days 00:17:18,0 days 00:17:18,16.8,0.000000,4.3,8.289017
2019-10-23 08:02:09,2019-10-24 07:42:32,1,8.38,1,32.0,1.0,0.5,5.5,0.0,0.3,...,2.5,This is a new column,This is a new column too,0 days 23:40:23,0 days 23:40:23,0 days 23:40:23,36.3,0.151515,4.3,0.353989

Reset Index
We can make pickup a column again with the reset_index() method:

In [43]:
taxis=taxis.reset_index()
taxis.head()

,index,pickup,dropoff,passenger_count,trip_distance,payment_type,fare_amount,extra,mta_tax,tip_amount,...,congestion_surcharge,new_column1,new_column2,trip_time1,trip_time2,elapsed_time,cost_before_tip,tip_pct,fees,avg_speed
0,0,2019-10-24 08:19:11,2019-10-24 09:00:35,0,13.20,2,42.0,0.0,0.5,0.0,...,0.0,This is a new column,This is a new column too,0 days 00:41:24,0 days 00:41:24,0 days 00:41:24,42.8,0.0,0.8,19.130435
1,1,2019-10-24 08:07:45,2019-10-24 08:07:50,2,0.00,2,52.0,0.0,0.5,0.0,...,2.5,This is a new column,This is a new column too,0 days 00:00:05,0 days 00:00:05,0 days 00:00:05,55.3,0.0,3.3,0.000000
2,2,2019-10-24 07:58:31,2019-10-24 08:47:05,1,0.00,1,22.2,0.0,0.5,0.0,...,0.0,This is a new column,This is a new column too,0 days 00:48:34,0 days 00:48:34,0 days 00:48:34,23.0,0.0,0.8,0.000000
3,3,2019-10-24 07:29:52,2019-10-24 07:33:24,1,0.54,2,4.0,0.0,0.5,0.0,...,0.0,This is a new column,This is a new column too,0 days 00:03:32,0 days 00:03:32,0 days 00:03:32,4.8,0.0,0.8,9.169811
4,4,2019-10-24 07:23:52,2019-10-24 08:08:52,1,0.00,1,36.2,0.0,0.5,0.0,...,0.0,This is a new column,This is a new column too,0 days 00:45:00,0 days 00:45:00,0 days 00:45:00,37.0,0.0,0.8,0.000000

Exercise 2
Read in the Meteorite_Landings.csv file.
Update the year column to only contain the year.
Convert it to a numeric data type.
Create a new column indicating whether the meteorite was observed falling before 1970.
Set the index to the id column and extract all the rows with IDs between 10,036 and 10,040 (inclusive) with loc[].

Hint 1: Use year.str.slice() to grab a substring.

Hint 2: Make sure to sort the index before using loc[] to select the range.

Bonus: There's a data entry error in the year column. Can you find it? (Don't spend too much time on this.)

In [78]:
#Solution

import pandas as pd
meteorites=pd.read_csv('../data/Meteorite_Landings.csv')
meteorites.head(2)  #1

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"

In [79]:
meteorites['year']=meteorites['year'].str.slice(6, 10)
meteorites.head() #2

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,1880,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,1902,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [85]:
#
meteorites['year'] = meteorites['year'].astype('Int64')
meteorites.dtypes #3

name            object
id               int64
nametype        object
recclass        object
mass (g)       float64
fall            object
year             Int64
reclat         float64
reclong        float64
GeoLocation     object
before_1970       bool
dtype: object

In [86]:
meteorites = meteorites.assign(
    before_1970=lambda x: x.year < 1970 
    ) # 4

meteorites.head(2)

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation,before_1970
0,Aachen,1,Valid,L5,21.0,Fell,1880,50.77500,6.08333,"(50.775, 6.08333)",True
1,Aarhus,2,Valid,H6,720.0,Fell,1951,56.18333,10.23333,"(56.18333, 10.23333)",True

In [87]:
meteorites = meteorites.set_index('id')
meteorites.head(3)

,name,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation,before_1970
id,,,,,,,,,,
1,Aachen,Valid,L5,21.0,Fell,1880,50.77500,6.08333,"(50.775, 6.08333)",True
2,Aarhus,Valid,H6,720.0,Fell,1951,56.18333,10.23333,"(56.18333, 10.23333)",True
6,Abee,Valid,EH4,107000.0,Fell,1952,54.21667,-113.00000,"(54.21667, -113.0)",True

In [89]:
meteorites = meteorites.sort_index()
meteorites.head(10)

,name,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation,before_1970
id,,,,,,,,,,
1,Aachen,Valid,L5,21.0,Fell,1880,50.77500,6.08333,"(50.775, 6.08333)",True
2,Aarhus,Valid,H6,720.0,Fell,1951,56.18333,10.23333,"(56.18333, 10.23333)",True
4,Abajo,Valid,H5,331.0,Found,1982,26.80000,-105.41667,"(26.8, -105.41667)",False
5,Abbott,Valid,H3-6,21100.0,Found,1951,36.30000,-104.28333,"(36.3, -104.28333)",True
6,Abee,Valid,EH4,107000.0,Fell,1952,54.21667,-113.00000,"(54.21667, -113.0)",True
7,Abernathy,Valid,L6,2914.0,Found,1941,33.85000,-101.80000,"(33.85, -101.8)",True
8,Abo,Valid,H,1.2,Found,1840,60.43333,22.30000,"(60.43333, 22.3)",True
9,Abu Moharek,Valid,H4,4500.0,Found,1997,27.23944,29.83583,"(27.23944, 29.83583)",False
10,Acapulco,Valid,Acapulcoite,1914.0,Fell,1976,16.88333,-99.90000,"(16.88333, -99.9)",False
11,Acfer 001,Valid,L6,6700.0,Found,1989,27.50000,3.61667,"(27.5, 3.61667)",False

In [95]:
meteorites.loc[10036:10040]

,name,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation,before_1970
id,,,,,,,,,,
10036,Enigma,Valid,H4,94.0,Found,1967,31.33333,-82.31667,"(31.33333, -82.31667)",True
10037,Enon,Valid,"Iron, ungrouped",763.0,Found,1883,39.86667,-83.95000,"(39.86667, -83.95)",True
10038,Enshi,Valid,H5,8000.0,Fell,1974,30.30000,109.50000,"(30.3, 109.5)",False
10039,Ensisheim,Valid,LL6,127000.0,Fell,1491,47.86667,7.35000,"(47.86667, 7.35)",True